CREATE TABLE IF NOT EXISTS public.urls (
    key BIGSERIAL NOT NULL PRIMARY KEY,
    url TEXT NOT NULL UNIQUE
);

GRANT SELECT, INSERT ON public.urls TO app;
GRANT USAGE, SELECT ON SEQUENCE urls_key_seq TO app;
